# Site settings
title: Coding with Aspen
header-img: img/home-bg.png
email: aspenjames@tqca.org
copyright_name: AspenJames
description: > # this means to ignore newlines until "baseurl:"
  Challenges and successes with coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AspenJames
learn_profile: AspenJames
email_username: aspenjames@tqca.org

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
